<?php
$this->jQuery()->enable();
echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');
echo $this->adminId;
//echo $this->form;
$this->tabPane("GTList", $this->form, array('title' => 'GT Add'));
echo $this->tabContainer("GTList", array());
echo $this->message;
?>
<script type="text/javascript">
    $(document).ready(function(){
	    $("input").blur(function(){
	    	if(this.value == "" || this.value == null)
	    	{
	    		return;
	    	}
	        var formElementId = ($(this).parent().prev().find('label').attr('for'));
	        doValidationPlant($(this).attr('id'),'../validation/validate?form=gasturbine');
	   });
	});
</script>