<?php
$this->jQuery()->enable();
echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');
$this->tabPane("GTEdit", $this->adminId.$this->form, array('title' => 'Edit Gasturbine'));
echo $this->tabContainer("GTEdit", array());
?>
<script type="text/javascript">
    $(document).ready(function(){
    $("input").blur(function(){
        var formElementId = ($(this).parent().prev().find('label').attr('for'));
        doValidation(formElementId,'/hive/public/gasturbine/editvalidate/');
   });
});
</script>