<?php
$list = NULL;
$list = $list . "<table>";
$role = Zend_Registry::get('role');
foreach ($this->GTdata as $gasturbines) {
    $list = $list . "<tr>";
    $list = $list . "<td><a href='" . $this->url(array('action' => 'view')) . "?id=" . $this->escape($gasturbines['GTId']) . "'>" . $gasturbines['GTName'] . "</a></td>";
    $role = Zend_Registry::get('role');
    $valid = false;
	if($role == 'sa')
	{
		$valid = true;
	}
    foreach ($this->gt as $temp) {
        if ((int) $temp['GTId'] == (int) $gasturbines['GTId']) {
            $valid = true;
        }
    }
    if($valid)
        $list = $list . "<td><a href='" . $this->url(array('action' => 'edit')) . "?id=" . $this->escape($gasturbines['GTId']) . "'>Edit</a></td>";
    $list = $list . "</tr>";
}
$list = $list . "</table>";
$this->tabPane("GTList", $list, array('title' => 'GT List'));
echo $this->tabContainer("GTList", array());
echo "<div style='padding:20px;'>".$this->paginationControl($this->GTdata,'Sliding','pagination.phtml')."</div>";
?>