<?php

if (count($this->GTData) == 0) {
    $list = "<center>No gasturbines added</center>";
}
else{
$pmodel = new Model_DbTable_Plant();
$gtdatamodel = new Model_DbTable_Gtdata();
foreach ($this->GTData as $gasturbines) {
    $list .=  "<div>";
    $list .=  "<span style='margin-right:10px;'><a href='/gasturbine/view?id=" . $this->escape($gasturbines['GTId']) . "'>" . $gasturbines['GTName'] . "</a></span>";
    $modelnum = Zend_Registry::get("gtgroupname");
    $list .=  "<span style='margin-right:10px;'>$modelnum</span>";
    $valid = false;
    foreach ($this->gt as $temp) {
        if ((int) $temp['GTId'] == (int) $gasturbines['GTId']) {
            $valid = true;
        }
    }
    $role = Zend_Registry::get('role');
    if ($valid || $role == 'sa') {
        $list .=  "<span class = 'gt-edit'><a href='/gasturbine/edit" . "?id=" . $this->escape($gasturbines['GTId']) . "' style='color: #719b3e;'>Edit</a></span>";
    }
    $list .=  "</div>";
    $fcount = $gtdatamodel->getTypeCount("finding", $gasturbines['GTId']);
    $ucount = $gtdatamodel->getTypeCount("upgrade", $gasturbines['GTId']);
    $lcount = $gtdatamodel->getTypeCount("lte", $gasturbines['GTId']);
    if ($fcount == 0) {
        $fline = "<span style='color: #ec2d19; margin-left: 15px;'>No Findings</span>";
    } else if ($fcount == 1) {
        $finding = $gtdatamodel->fetchRow("type = 'finding' AND gtid = " . $gasturbines['GTId']);
        $fid = $finding['id'];
        $fline = "<a href = '/gasturbine/view?id=" . $gasturbines['GTId'] . "#ui-tabs-2' style='color: #2e4e68;'>1 Finding</a>";
    } else {
        $fline = "<a href = '/gasturbine/view?id=" . $gasturbines['GTId'] . "#ui-tabs-2' style='color: #2e4e68;'>" . $fcount . " Findings</a>";
    }
    if ($ucount == 0) {
        $uline = "<span style='color: #ec2d19; margin-left: 15px;'>No Upgrades</span>";
    } else if ($ucount == 1) {
        $upgrade = $gtdatamodel->fetchRow("type = 'upgrade' AND gtid = " . $gasturbines['GTId']);
        $uid = $upgrade['id'];
        $uline = "<a href = '/gasturbine/view?id=" . $gasturbines['GTId'] . "#ui-tabs-3' style='color: #2e4e68;'>1 Upgrade</a>";
    } else {
        $uline = "<a href = '/gasturbine/view?id=" . $gasturbines['GTId'] . "#ui-tabs-3' style='color: #2e4e68;'>" . $ucount . " Upgrades</a>";
    }
    if ($lcount == 0) {
        $lline = "<span style='color: #ec2d19; margin-left: 15px;'>No LTEs</span>";
    } else if ($lcount == 1) {
        $lte = $gtdatamodel->fetchRow("type = 'lte' AND gtid = " . $gasturbines['GTId']);
        $lid = $lte['id'];
        $lline = "<a href = '/gasturbine/view?id=" . $gasturbines['GTId'] . "#ui-tabs-4' style='color: #2e4e68;'>1 LTE</a>";
    } else {
        $lline = "<a href = '/gasturbine/view?id=" . $gasturbines['GTId'] . "#ui-tabs-4' style='color: #2e4e68;'>" . $lcount . " LTEs</a>";
    }
    $plant = $pmodel->getPlant($gasturbines['plantId']);
    $pname = $plant['plantName'];
    $pid = $gasturbines['plantId'];
    $list .= "<div style='padding:15px; padding-left: 0px;'>";
    $list .= "<span>$fline, </span>";
    $list .= "<span>$uline, </span>";
    $list .= "<span>$lline</span>";
    $list .= "</div>";
    $list .= "<hr/><br/>";
}
}
$lastlogin = Zend_Auth::getInstance()->getStorage()->read()->lastlogin;
if ($lastlogin == NULL) {
    $list .= "<center><a href = '/plant/view?id=$pid'>&lt;&lt; Back &nbsp;&nbsp;</a>";
    $list .= "<a href = '/dashboard/index'>Continue &gt;&gt;</a></center>";
}
$this->tabPane("GTList", $list, array('title' => 'GT List'));
echo $this->tabContainer("GTList", array());
if (count($this->GTData) != 0) {
    echo "<div style='padding:20px;'>" . $this->paginationControl($this->GTData, 'Sliding', 'pagination.phtml') . "</div>";
}
?>