<?php
	if($this->ssid == 0)
		echo "<option value = '' selected = 'selected'>Select an Option</option>";
	else
		echo "<option value = ''>Select an Option</option>";
	$i=0;
	foreach($this->sslist as $list)
	{
		if($list['subSysName'] == "-")
		{
			continue;
		}
		if($list['id'] == $this->ssid)
		{
			$i++;
			echo "<option value = '".$list['id']."' selected = 'selected'>".$list['subSysName']."</option>";	
		}
		else{
			echo "<option value = '".$list['id']."'>".$list['subSysName']."</option>";
		}
		
	}
?>