<?php

foreach($this->plist as $pvalue){	
		$pres = $this->presmodel->getPresentation(key($pvalue));
		$filetype = $pres['filetype'];
		$h = 30;
		$w = 30;
		 if($filetype == 'doc' || $filetype == 'docx')
		 {
		 	$filename = "images/word.png";
			$list=$list."<a href='/presentation/view/?id=".$this->escape(key($pvalue))."'><img src = '/".$filename."' height = $h width = $w>".current($pvalue)."</a><br>";
		 }
		 else if($filetype == 'xls' || $filetype == 'xlsx')
		{
			$filename = "images/excel.png";
			$list=$list."<a href='/presentation/view/?id=".$this->escape(key($pvalue))."'><img src = '/".$filename."' height = $h width = $w>".current($pvalue)."</a><br>";
		}
		else if($filetype == 'ppt' || $filetype == 'pptx')
		{
			$filename = "images/ppt.png";
			$list=$list."<a href='/presentation/view/?id=".$this->escape(key($pvalue))."'><img src = '/".$filename."' height = $h width = $w>".current($pvalue)."</a><br>";
		}
		else if($filetype == 'pdf')
		{
			$filename = "images/pdf.png";
			$list=$list."<a href='/presentation/view/?id=".$this->escape(key($pvalue))."'><img src = '/".$filename."' height = $h width = $w>".current($pvalue)."</a><br>";
		}
		 else {
		 	$h = 300;
			 $w = 400;
		 	$filename = "random/thnail" . rand(0,999999);
			$data = $pres['content'];
			file_put_contents($filename,$data);
			$ilist=$ilist."<a href='/presentation/view/?id=".$this->escape(key($pvalue))."'><img src = '/".$filename."' height = $h width = $w>".current($pvalue)."</a><br>";
		 }
     
}
$list .= $ilist;
$ssModel = $this->subSysModel;
$ss = $ssModel->getSubSystem($this->finding['subSysId']);
$system = $this->sysModel->getSystem($this->finding['sysId']);
$dataid = $this->finding['id'];

$role = Zend_Registry::get("role");
$uid = Zend_Auth::getInstance()->getStorage()->read()->id;
$umodel = new Model_DbTable_Userprofile();
$user = $umodel->getUser($uid);
$upid = $user['plantId'];
$gtid = $this->finding['gtid'];
$gtmodel = new Model_DbTable_Gasturbine();
$gt = $gtmodel->getGT($gtid);
$gtpid = $gt['plantId'];
$valid = false;
if($upid == $gtpid || $role == 'sa')
{
	$editlink = "<div style='float:left;' class='gt-edit'><a href = '/findings/edit?id=$dataid' style='color: #719b3e;'>Edit</a></div>";
}


$content = $content . "<div class='gtdata-title'>".$this->finding['title'];
if($ss['subSysName'] == "-")
{
	$content = $content." <span style='color:#77B464;'>".$system['sysName'] ."</span>";
}
else
{
	$content = $content." <span style='color:#77B464;'>".$system['sysName'] . "/" . $ss['subSysName'] ."</span>";
}
$content = $content." <span style='color:#268FBB;'>".$this->gt['GTName']."</span><br/>";
if($this->finding['EOH'] != 0 && $this->finding['EOH'] != "")
	$content = $content." <span style='color:#268FBB;'><b>EOH at Occurence</b>: ". $this->finding['EOH']."</span>";
if($this->finding['DOF'] != "" && $this->finding['DOF'] != "0000-00-00")
	$content = $content." <span style='color:#268FBB;'><b>Date of Finding</b>: ".$this->finding['DOF']."</span>";
if($this->finding['TOI'] != "")
	$content = $content." <span style='color:#268FBB;'><b>Type of Inspection</b>: ".$this->finding['TOI']."</span><br>";
$content = $content." <span style='color:#268FBB; font-size: 12px; font-style: normal; font-weight:bold;'>Updated On ".$this->finding['updatedate']."</span></div>";
$content = $content."<div class='gtdata-data'>".$this->finding['data']."</div>";
if($list == "")
	$list="<span style='color:#d95e1c;'>No Attachments Added</span>";
$content = $content."<div class='gtdata-presentations'><div style='font-size: 16px; padding-bottom: 5px;'>Attachments:</div>$list</div>";

$content = $content .$editlink;

$content = $content . "<form action = '/reports/generate' method = 'post' style='float:right'>
	<input type = 'hidden' name = 'type' value = 'finding'>
	<input type = 'hidden' name = 'id' value = '".$this->finding['id']."'>
	<input class = 'gt-report' type = 'submit' name = 'report' value = 'Generate Findings Report'>
</form>"; 
$content = $content . "<div align='right'>
	<form action = '/reports/configure?id=".$this->finding['id']."&type=gtdataview' method = 'post'>
		<input class = 'gt-configure' type = 'submit' name = 'reportgen' value = 'Configure Report'>
	</form>
</div>";

$content = $content ."<div style='clear:both; height:5px;'>&nbsp;</div>";

$this->tabPane("findingView",$content,array('title' => 'Finding View'));
echo $this->tabContainer("findingView",array());
?>