<?php

foreach($this->plist as $pvalue){
	$pres = $this->presmodel->getPresentation(key($pvalue));
	$filetype = $pres['filetype'];
	$h = 30;
	$w = 30;
	 if($filetype == 'doc' || $filetype == 'docx')
	 {
	 	$filename = "images/word.png";
	 }
	 else if($filetype == 'xls' || $filetype == 'xlsx')
	{
		$filename = "images/excel.png";
	}
	else if($filetype == 'ppt' || $filetype == 'pptx')
	{
		$filename = "images/ppt.png";
	}
	else if($filetype == 'pdf')
	{
		$filename = "images/pdf.png";
	}
	 else {
	 	$h = 300;
		 $w = 400;
	 	$filename = "random/thnail";
		$data = $pres['content'];
		file_put_contents($filename,$data);
	 }
	 
     $list=$list."<a href='".$this->baseUrl()."/presentation/view/?id=".$this->escape(key($pvalue))."'><img src = '../".$filename."' height = $h width = $w>".current($pvalue)."</a><br>";
}
$ssModel = $this->subSysModel;
$ss = $ssModel->getSubSystem($this->finding['subSysId']);
$system = $this->sysModel->getSystem($ss['sysId']);
$dataid = $this->finding['id'];
$editlink = "<div style='float:left;' class='gt-edit'><a href = '/findings/edit?id=$dataid' style='color: #719b3e;'>Edit</a></div>";

$content = $content . "<div class='gtdata-title'>".$this->finding['title'];
$content = $content." <span style='color:#77B464;'>".$system['sysName'] . "/" . $ss['subSysName'] ."</span>";
$content = $content." <span style='color:#268FBB;'>".$this->gt['GTName']."</span><br/>";
$content = $content." <span style='color:#268FBB; font-size: 12px; font-style: normal; font-weight:bold;'>Updated On ".$this->finding['updatedate']."</span></div>";
$content = $content."<div class='gtdata-data'>".$this->finding['data']."</div>";
if($list == "")
	$list="<span style='color:#d95e1c;'>No Attachments Added</span>";
$content = $content."<div class='gtdata-presentations'><div style='font-size: 16px; padding-bottom: 5px;'>Attachments:</div>$list</div>";

$content = $content .$editlink;

$content = $content . "<form action = '/reports/generate' method = 'post' style='float:right'>
	<input type = 'hidden' name = 'type' value = 'finding'>
	<input type = 'hidden' name = 'id' value = '".$this->finding['id']."'>
	<input class = 'gt-report' type = 'submit' name = 'report' value = 'Generate Findings Report'>
</form>"; 
$content = $content . "<div align='right'>
	<form action = '/reports/configure?id=".$this->finding['id']."&type=gtdataview' method = 'post'>
		<input class = 'gt-configure' type = 'submit' name = 'reportgen' value = 'Configure Report'>
	</form>
</div>";

$content = $content ."<div style='clear:both; height:5px;'>&nbsp;</div>";

$this->tabPane("findingView",$content,array('title' => 'Finding View'));
echo $this->tabContainer("findingView",array());
?>




