<?php
	$i=1;
	echo "<br><br><br>";
	foreach($this->schlist as $sch)
	{
		echo $i . "&nbsp;&nbsp;&nbsp;" . $sch['event_date'] . "&nbsp;&nbsp;&nbsp;" .
		$sch['description'] . "<a href = '/schedule/delevent?id=" . $sch['event_id'] .
		"&schid=".$sch['sch_id']."'>Delete Event</a><br><br>";
		$i++;
	}
	
	echo "<form action = '/schedule/delsch?id=" . $this->schid . "' method = 'post'>
	<input type = 'submit' value = 'Delete Full Schedule'></form>";
	
?>

