<?php
$this->jQuery()->enable();
echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');
echo $this->adminId;
echo $this->form;
?>
<script type="text/javascript">
    $(document).ready(function(){
    $("input").blur(function(){
        var formElementId = ($(this).parent().prev().find('label').attr('for'));
        doValidation(formElementId,'/hive/public/advertisement/addvalidate/');
   });
});
</script>