<br /><br /><center>View script for controller <b>Registration</b> and script/action name <b>index</b></center>

<table>
<tr>
<th>Username</th>
<th>Role</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->paginator as $user) : ?>
<tr>
<td><?php echo $this->escape($user['username']);?></td>
<td><?php echo $this->escape($user['role']);?></td>
<td>
<form action="<?php echo $this->url(array('action'=>'deleteacc')); ?>" method="post">
<input type="hidden" name="id" value="<?php echo $this->escape($user['id']);?>" />
<input type="submit" name="del" value="Delete" />
</form>
</td>
<td>
<form action="<?php echo $this->url(array('action'=>'resetpassword')); ?>" method="post">
<input type="hidden" name="id" value="<?php echo $this->escape($user['id']);?>" />
<input type="submit" name="resetpass" value="Reset Password" />
</form>
</td>
<td>
<form action="<?php echo $this->url(array('action'=>'transform')); ?>" method="post">
<input type="hidden" name="id" value="<?php echo $this->escape($user['id']);?>" />
<input type="submit" name="transform" value="Transform" />
</form>
</tr>
<?php endforeach; ?>
</table>

<?php

echo $this->paginationControl($this->paginator,'Sliding','pagination.phtml');