<?php 
	if(!count($this->users))
	{
		echo "<center>No users added</center>";
		return;
	}
?>
<script type="text/javascript" src="/js/tablecloth/tablecloth.js"></script>
<link href='/js/tablecloth/tablecloth.css' rel='stylesheet' type='text/css' />
<?php $role = Zend_Registry::get('role'); ?>
<table cellspacing="1" id="tables" onmouseover="tablecloth();">
<thead>
<tr>
<th>Username</th>
<th>Name</th>
<th>Role</th>
<?php if($role == 'sa'){
echo "<th></th><th></th><th></th>";
} else{
  echo "<th></th>";
}
?>
</tr>
</thead>
<tbody>
<?php foreach($this->users as $user) : ?>
<tr>
<td><?php echo "<a href = '/userprofile/view?id=". $user['id'] . "'>" . $this->escape($user['username']) . "</a>";?></td>
<td><?php echo $this->escape($user['firstName']).' '.$this->escape($user['lastName']); ?></td>
<td><?php echo $this->escape($user['role']);?></td>

<?php if($user['role'] == 'sa') : ?>
<td>
<form action="<?php echo $this->url(array('action'=>'deleteacc')); ?>" method="post">
<input type="hidden" name="id" value="<?php echo $this->escape($user['id']);?>" />
<input class='gt-delete' type="submit" name="del" value="Delete"/>
</form>
</td>
<?php endif; ?>
<td>
<form action= "/administration/resetpassword?source=adminlist" method="post">
<input type="hidden" name="id" value="<?php echo $this->escape($user['id']);?>" />
<input class="reset-button" type="submit"  name="resetpass" value="Reset Password" />
</form>
</td>

<?php
	if($role != 'sa') { continue ;}
	if($this->validcc==0){
		
		echo "<td><form action = '/administration/setcc?id=".$user['id']."' method='post'>";
		echo "<input class='gt-add' type='submit' name='setcc' value = 'Set Conference Chairman'>";
		echo "</form></td>";
	}
	else{
		if($this->validcc==$user['id']){
			echo "<td><form action = '/administration/unsetcc?id=".$user['id']."' method='post'>";
			echo "<input class='gt-delete' type='submit' name='setcc' value = 'Unset Conference Chairman'>";
			echo "</form></td>";
		}
	}
			
?>
</tr>
<?php endforeach; ?>
</tbody>
</table>

<script type = "text/javascript">
	$(".reset-button").click(function(){
		alert("Password has been reset. Please check mail");
	});
</script>