<script type="text/javascript" src="/js/tablecloth/tablecloth.js"></script>
<link href='/js/tablecloth/tablecloth.css' rel='stylesheet' type='text/css' />
<?php $role = Zend_Registry::get('role'); ?>
<table cellspacing="1" id="tables" class="tablesorter" onmouseover="tablecloth();">
<thead>
<tr>
<th>Username</th>
<th>Name</th>
<th>Role</th>
<?php if($role == 'sa') : ?>
<th></th>
<th></th>
<?php endif; ?>
<th></th>
</tr>
</thead>
<tbody>
<?php foreach($this->users as $user) : ?>
<tr>
<td><?php echo $this->escape($user['username']);?></td>
<td><?php echo $this->escape($user['firstName']).' '.$this->escape($user['lastName']); ?></td>
<td><?php echo $this->escape($user['role']);?></td>
<td>

<form action="<?php echo $this->url(array('action'=>'deleteacc')); ?>" method="post">
<input type="hidden" name="id" value="<?php echo $this->escape($user['id']);?>" />
<?php if($user['role'] == 'sa') : ?>
<input type="submit" name="del" value="Delete"	/>
<?php endif; ?>
</form>

</td>
<td>
<form action="<?php echo $this->url(array('action'=>'resetpassword')); ?>" method="post">
<input type="hidden" name="id" value="<?php echo $this->escape($user['id']);?>" />
<input type="submit" name="resetpass" value="Reset Password" />
</form>
</td>

<?php
	if($role != 'sa') { continue ;}
	if($this->validcc==0){
		
		echo "<td><form action = '/administration/setcc?id=".$user['id']."' method='post'>";
		echo "<input type='submit' name='setcc' value = 'Set Conference Chairman'>";
		echo "</form></td>";
	}
	else{
		if($this->validcc==$user['id']){
			echo "<td><form action = '/administration/unsetcc?id=".$user['id']."' method='post'>";
			echo "<input type='submit' name='setcc' value = 'Unset Conference Chairman'>";
			echo "</form></td>";
		}
	}
			
?>
</tr>
<?php endforeach; ?>
</tbody>
</table>