<script type="text/javascript">
            ddsmoothmenu.init({
                mainmenuid: "smoothmenu1", //menu DIV id
                orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
                classname: 'ddsmoothmenu', //class added to menu's outer DIV
                customtheme: ["#2e4e68", "#00192c"],
                contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
            });
</script>

<div id="smoothmenu1" class="ddsmoothmenu" >
<?php
	echo $this->navigation()->menu();
?>
</div>