<?php
$this->jQuery()->enable();
echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxbookmark.js');
?>

<?php if($this->result):?>
<div id="bookmark-container">
    <button id="remove-bookmark" onclick="removeBookmark('<?php echo $this->escape($this->id);?>','normal')">Remove Bookmark</button>
</div>
<?php endif; ?>

<?php if(!$this->result): ?>
<div id="bookmark-container">
    <button id="add-bookmark" onclick="addBookmark('<?php echo $this->escape($this->controller); ?>','<?php echo $this->escape($this->id);?>')">Add Bookmark</button>
</div>
<?php endif; ?>
