<?php
$existPresList = "<b>Attachments already added to this</b><br><br>";
$pres_str = substr($this->gtdata['presentationId'],0,strlen($this->gtdata['presentationId'])-1);
$pres_array = explode(",",$pres_str);

$presmodel = new Model_DbTable_Presentation();
for($i=0;$i<count($pres_array);$i++)
{
	$pres = $presmodel->getPresentation($pres_array[$i]);
	$existPresList .= "<a href = '/presentation/view?id=" . $pres_array[$i] . "'>" . $pres['title'] . "</a>";
	$existPresList .= "<form action = '/presentation/unlink' method = post>";
	$existPresList .= "<input type = 'hidden' name = 'id' value = '" . $pres_array[$i] . "'>";
	$existPresList .= "<input type = 'hidden' name = 'gtdataid' value = '" . $this->gtdata['id'] . "'>";
	$existPresList .= "<input type = 'submit' class = 'gt-delete' value = ''></form><br>";
}
echo $this->headScript()->prependFile($this->baseUrl().'/js/tiny_mce/tiny_mce.js');
$this->jQuery()->enable();
$this->tabPane("UpgradeEdit",$existPresList .$this->form . "<br>" . $this->message,array('title' => 'Upgrade Edit'));
echo $this->tabContainer("UpgradeEdit",array());
?>
<script type="text/javascript" src='/js/tinyMCEinit.js'></script>
<div id = "spinnerimage" style = "display:none">Uploading ... <img src = "/images/spinner.gif"></div>
<script type = "text/javascript">
	$(document).ready(function(){
	$("#submitbutton").click(function() {
		var file = document.getElementById("content").value;
		if (file != "")
		{
			document.getElementById("spinnerimage").style.display = "block";
		}
	});
    $("#sysId").change( function() {
        $.ajax({
            type: "POST",
            data: "id=" + $(this).val(),
            url: "/findings/index",
            success: function(msg){
                if (msg != ''){
                    $("#subSysId").html(msg).show();
                    
                }
            }
        });
    });
});
</script>