<div style="padding-left:20px">
<h2>Manage Users in other Plants</h2>
<?php
try {
    $this->jQuery()->enable();
	//$currentgitcommit = Zend_Registry::get('currentgitcommit');
	//echo "Current GIT Commit Name - '" . $currentgitcommit . "'";
    echo $this->headScript()->prependFile($this->baseUrl().'/js/frontend.js');
    $i=0;
    foreach($this->plants as $plant) {
        echo $this->accordionPane('plants',"Loading Content... Please Wait...",
                                  array('title' => $plant['plantName']),
                                  array('id' => $plant['plantId'])
                                  );
        echo "<div style = 'display:none'><form><input type = 'hidden' id = 'plant".$i++."' value = '".$plant['plantId']."'></form></div>";
    }
    echo $this->accordionContainer('plants',array('active'=>'none','collapsible'=>'true','autoHeight' => 'true'));
}
catch(Exception $e){
    echo $e;
}
?>
</div>
<?php
    echo "<div style='padding:20px;'>".$this->paginationControl($this->plants,'Sliding','accpagination.phtml')."</div>";
?>