<?php
$list = NULL;
$list = $list . "<table>";
$role = Zend_Registry::get('role');
foreach ($this->Pdata as $plant) {
    $list = $list . "<tr>";
    $list = $list . "<td><a href='" . $this->url(array('action' => 'view')) . "?id=" . $this->escape($plant['plantId']) . "'>" . $plant['plantName'] . "</a> (" . $plant['corporateName'] . ")</td>";
    if($this->pid == $plant['plantId'] || $role == 'sa')
        $list = $list . "<td><a href='" . $this->url(array('action' => 'edit')) . "?id=" . $this->escape($plant['plantId']) . "'>Edit</a></td>";
    $list = $list . "</tr>";
}
$list = $list . "</table>";
$this->tabPane("PList", $list, array('title' => 'Plant List'));
echo $this->tabContainer("PList", array());
echo "<div style='padding:20px;'>".$this->paginationControl($this->Pdata,'Sliding','pagination.phtml')."</div>";
?>