<div id='search-results'>
		<center><h2><span style='background-color: #e5f1fa; padding: 5px; font-weight:normal;' class='ui-corner-all'> <?php echo count($this->searchData) + count($this->forumData); ?> search results for <?php echo substr($this->queryStr, 0, strlen($this->queryStr) - 1); ?></span></h2></center>
        <?php
        $this->queryStr = substr($this->queryStr, 0, strlen($this->queryStr) - 1);
        $sysmodel = new Model_DbTable_Gtsystems();
        $subsysmodel = new Model_DbTable_Gtsubsystems();
        $gtmodel = new Model_DbTable_Gasturbine();
        $pmodel = new Model_DbTable_Plant();
        $umodel = new Model_DbTable_Userprofile();
		$i=1;
        ?>
		
        <?php
        $gtmodel = new Model_DbTable_Gasturbine();
		$pmodel = new Model_DbTable_Plant();
		$sysmodel = new Model_DbTable_Gtsystems();
		$subsysmodel = new Model_DbTable_Gtsubsystems();
		$umodel = new Model_DbTable_Userprofile();
        foreach ($this->searchData as $data) : ?>
        <?php
        	//$data['data'] = strip_tags($data['data'],'<b>');
            
            
            $gt = $gtmodel->getGT($data['gtid']);
            $plant = $pmodel->getPlant($gt['plantId']);
			
            $user = $umodel->getUser($data['userupdate']);
			$uplant = $pmodel->getPlant($user['plantId']);
            $username = $user['firstName'] . "  " . $user['lastName'];
			$uplantname = $uplant['plantName'];
			$pos = strpos($data['data'],$this->queryStr);
			
			if($pos)
			{
				if(($pos-200) < 0)
				{
					$start = 0;
				}
				else {
					$start = $pos-200;
				}
				if(($pos+200) > strlen($data['data']))
				{
					$end = strlen($data['data']);
				}
				else {
					$end = $pos + 200;
				}
				if($start == 0)
				{
					$searchData = substr($data['data'],$start,$end) . " ...";
				}
				else {
					$searchData = "... " . substr($data['data'],$start,$end) . " ...";
				}
			}
			else {
	            if (strlen($data['data']) <= 400) {
	                $searchData = $data['data'];
	            } else {
	                $searchData = substr($data['data'], 0, 400) . " ...";
	            }
			}
			
        ?>
        	
	    <div class = 'tendivgt search-result' id = 'tengroup<?php echo $i; ?>' onmouseover="glow(this,'f0f7ec'); this.style.borderLeft='solid 2px #2e4e68';" onmouseout="unglow(this); this.style.borderLeft='none';">
	    
	    <div class='search-result-title'><?php echo "<a href = '" . $this->baseUrl() . $data['url'] . "'>" . $data['title']; ?><i>(<?php echo ucfirst($data['type']); ?>)</i></a></div>
	    <b><div class='search-result-details'><span class='search-result-ss'><?php echo $data['sysname'] . " / " . $data['subsysname']; ?>   </span>
	    <span class='search-result-gt'><?php echo $gt['GTName']; ?></span>
		<span class='search-result-plant'><?php echo $plant['plantName']; ?></span></div></b>
	    <div class='search-result-data'><?php echo $searchData ?></div>
	    <div class='search-result-updatedby'><i> Updated by <?php echo $data['username'] . " - " . $data['userplantname'] ; ?> &nbsp;on <?php echo $data['updatedate']; ?></i></div>
		
		</div>
		<?php if(($i%10) == 0) : ?>
		<div class = 'showmoregt' onclick = "showten(<?php echo (int)$i/10; ?>)" id = 'hidegroup<?php echo (int)($i/10);?>'><h2>Show More Results</h2></div>
		<?php endif; ?>
<?php
$i++;
endforeach; 
$i=1;?>
<?php
            $forumModel = new Model_DbTable_Forum_Data();
            $topicModel = new Model_DbTable_Forum_Topics();
            $postModel = new Model_DbTable_Forum_Posts();
            $uModel = new Model_DbTable_Userprofile();
            foreach ($this->forumData as $fdata) :
                $topic = $topicModel->getTopic($fdata['topic_id']);
                $post = $postModel->getPost($fdata['post_id']);
                $user = $uModel->getUser($fdata['poster_id']);
                $username = $user['firstName'] . " " . $user['lastName'];
				$uplant = $pmodel->getPlant($user['plantId']);
				$uplantname = $uplant['plantName'];
?>		
		
		</div>


				<div class = 'tendivf search-result' id = 'tengroupf<?php echo $i; ?>' onmouseover="glow(this,'f0f7ec'); this.style.borderLeft='solid 2px #2e4e68';" onmouseout="unglow(this); this.style.borderLeft='none';">
        		<b><div class='search-result-details'>
				<div class='search-result-ss'><?php echo "<a href = '" . $fdata['url'] . "'>" . $fdata['post_subject'] . "</a>"; ?></div>
        		<div class='search-result-gt'>Topic : <?php echo $fdata['topicname']; ?></div>
        		<div class='search-result-plant'>Subject : <?php echo $fdata['post_subject']; ?></div></div></b>
        		<div class='search-result-data'><?php echo $fdata['post_text']; ?></div>
                <div class='search-result-updatedby'><i>Posted by <?php echo $fdata['postername'] . " - " . $fdata['userplantname'] . " "; ?></i></div>
                </div>
                <?php if(($i%10) == 0) : ?>
				<div class = 'showmoref' onclick = "showtenf(<?php echo (int)$i/10; ?>)" id = 'hidegroupf<?php echo (int)($i/10);?>'><h2>Show More Results</h2></div>
				<?php endif; ?>
        <?php
        		$i++;
                endforeach;	
                if (!count($this->forumData) && !count($this->searchData)) {
                    echo "<center><i>No results to display</i></center>";
                }
        ?>		
		
</div>

<script type = "text/javascript">
	var showmoregt = document.getElementsByClassName("showmoregt");
	var i = 0;
	for(i=0;i<showmoregt.length;i++)
	{
		if(showmoregt[i].id != "hidegroup1")
		{
			showmoregt[i].style.display = "none";
		}	
	}
	
	var tengroup = document.getElementsByClassName("tendivgt");
	var i =0;
	for(i=0;i<tengroup.length;i++)
	{
		if(Math.floor(i/10) != 0)
		{
			tengroup[i].style.display = "none";
		}
	}
	
	var showmore = document.getElementsByClassName("showmoref");
	var i = 0;
	for(i=0;i<showmore.length;i++)
	{
		if(showmore[i].id != "hidegroupf1")
		{
			showmore[i].style.display = "none";
		}	
	}
	
	var tengroup = document.getElementsByClassName("tendivf");
	var i =0;
	for(i=0;i<tengroup.length;i++)
	{
		if(Math.floor(i/10) != 0)
		{
			tengroup[i].style.display = "none";
		}
	}
	
	function showten(group)
	{
		var e = document.getElementsByClassName("tendivgt");
		var i = 0;
		for(i=0;i<e.length;i++)
		{
			if(Math.floor(i/10) == (group))
			{
				e[i].style.display = "block";
			}
		}
		document.getElementById("hidegroup"+(group + 1)).style.display = "block";
	}
	
	function showtenf(group)
	{
		var e = document.getElementsByClassName("tendivf");
		var i = 0;
		for(i=0;i<e.length;i++)
		{
			if(Math.floor(i/10) == (group))
			{
				e[i].style.display = "block";
			}
		}
		document.getElementById("hidegroupf"+(group + 1)).style.display = "block";
	}
</script>
