<script type = "text/javascript">
	
	function gtpaginate(i)
	{
		var ll = (i-1) * 10;
		var ul = ll + 10;
		ll = ll + 1;
		var query = document.getElementById("query").innerHTML;
		$.ajax({
            data: "keyword=" + query + "&ll=" + ll + "&ul=" + ul + "&cat=gt",
            url: "/search/view",
            success: function(msg){
                if (msg != ''){
                    $("#gtdata-search-results").html(msg);
                    
                }
            }
        });
	}
	
	
	function fpaginate(i)
	{
		var ll = (i-1) * 10;
		var ul = ll + 10;
		ll = ll + 1;
		var query = document.getElementById("query").innerHTML;
		$.ajax({
            data: "keyword=" + query + "&ll=" + ll + "&ul=" + ul + "&cat=forum",
            url: "/search/view",
            success: function(msg){
                if (msg != ''){
                    $("#forum-search-results").html(msg);
                    
                }
            }
        });
	}
</script>


<div id='search-results'>
	<div id = "gtdata-search-results">
		<?php 
if($this->tgr != 0) :?>
<center><h2><span style='background-color: #e5f1fa; padding: 5px; font-weight:normal;' class='ui-corner-all'> <?php echo $this->tgr ;?> search results from Gasturbine Data</span></h2></center>
<?php echo "<center><h3>Showing results " . $this->ll . " to " . $this->ul . " of " . $this->tgr . "</h3></center>"; ?>

<?php endif; ?>
        <?php
        $this->queryStr = substr($this->queryStr, 0, strlen($this->queryStr) - 1);
        $sysmodel = new Model_DbTable_Gtsystems();
        $subsysmodel = new Model_DbTable_Gtsubsystems();
        $gtmodel = new Model_DbTable_Gasturbine();
        $pmodel = new Model_DbTable_Plant();
        $umodel = new Model_DbTable_Userprofile();
        ?>
		
        <?php
        $gtmodel = new Model_DbTable_Gasturbine();
		$pmodel = new Model_DbTable_Plant();
		$sysmodel = new Model_DbTable_Gtsystems();
		$subsysmodel = new Model_DbTable_Gtsubsystems();
		$umodel = new Model_DbTable_Userprofile();
		$i = 1;
        foreach ($this->searchData as $data) : ?>
        <?php
        	
        	$data['data'] = strip_tags($data['data']);
            
            $gt = $gtmodel->getGT($data['gtid']);
            $plant = $pmodel->getPlant($gt['plantId']);
			
            $user = $umodel->getUser($data['userupdate']);
			$uplant = $pmodel->getPlant($user['plantId']);
            $username = $user['firstName'] . "  " . $user['lastName'];
			$uplantname = $uplant['plantName'];
			$pos = strpos($data['data'],$this->queryStr);
			
			if($pos)
			{
				if(($pos-200) < 0)
				{
					$start = 0;
				}
				else {
					$start = $pos-200;
				}
				if(($pos+200) > strlen($data['data']))
				{
					$end = strlen($data['data']);
				}
				else {
					$end = $pos + 200;
				}
				if($start == 0)
				{
					$searchData = substr($data['data'],$start,$end) . " ...";
				}
				else {
					$searchData = "... " . substr($data['data'],$start,$end) . " ...";
				}
			}
			else {
	            if (strlen($data['data']) <= 400) {
	                $searchData = $data['data'];
					
	            } else {
	                $searchData = substr($data['data'], 0, 400) . " ...";
	            }
			}
			
        ?>
        	
	    <div class = 'tendivgt search-result' id = 'tengroup<?php echo $i; ?>' onmouseover="glow(this,'f0f7ec'); this.style.borderLeft='solid 2px #2e4e68';" onmouseout="unglow(this); this.style.borderLeft='none';">
	    
	    <div class='search-result-title'><?php echo "<a href = '"  . $data['url'] . "'>" . Model_Functions::highlightResults($this->queryStr,$data['title']); ?><i> (<?php echo Model_Functions::highlightResults($this->queryStr,ucfirst($data['type'])); ?>) </i></a></div>
	    <b><div class='search-result-details'><span class='search-result-ss'><?php echo Model_Functions::highlightResults($this->queryStr,$data['sysname']) . " / " . Model_Functions::highlightResults($this->queryStr,$data['subsysname']); ?>   </span>
	    <span class='search-result-gt'><?php echo "<a href = '/gasturbine/view?id=" . $gt['GTId'] . "'>" . $gt['GTName'] . "</a>"; ?></span>
		<span class='search-result-plant'><?php echo "<a href = '/plant/view?id=" . $plant['plantId'] . "'>" . Model_Functions::highlightResults($this->queryStr,$plant['plantName']) . "</a>"; ?></span></div></b>
	    <div class='search-result-data'><?php echo Model_Functions::highlightResults($this->queryStr,$searchData) ?></div>
	    <div class='search-result-updatedby'><i> Updated by <?php echo "<a href = '/userprofile/view?id=" . $data['userupdate'] . "'>" .$username . "</a> - <a href = '/plant/view?id=" . $user['plantId'] . "'>"  .Model_Functions::highlightResults($this->queryStr,$data['userplantname']) . "</a>" ; ?> &nbsp;on <?php echo $data['updatedate']; ?></i></div>
		
		</div><br>
<?php
endforeach; 
?>

	<div id = "query" style = "display: none"><?php echo $this->queryStr; ?></div>
	<div id = "gt-pagination">
		<?php
			$results = $this->tgr;
			$n = (int)($results/10);
			if($results % 10 != 0)
			{
				$n++;
			}
			if($n != 1)
			{
				
				for($i=1;$i<=$n;$i++)
				{
					
					echo "<a href = '#' id = 'gt_paginate_link' onclick = 'gtpaginate($i)'>" . $i . "</a>&nbsp&nbsp";
				}
			}
		?>
	</div>
</div>

<div id = "forum-search-results">
<?php 
if($this->fgr != 0) :
?>
<center><h2><span style='background-color: #e5f1fa; padding: 5px; font-weight:normal;' class='ui-corner-all'> <?php echo $this->fgr ;?> search results from Forum Discussion</span></h2></center>
<?php echo "<center><h3>Showing results " . $this->ll . " to " . $this->ul . " of " . $this->fgr . "</h3></center>"; ?>

<?php endif; ?>

<?php
            $forumModel = new Model_DbTable_Forum_Data();
            $topicModel = new Model_DbTable_Forum_Topics();
            $postModel = new Model_DbTable_Forum_Posts();
            $uModel = new Model_DbTable_Userprofile();
            foreach ($this->forumData as $fdata) :
                $topic = $topicModel->getTopic($fdata['topic_id']);
                $post = $postModel->getPost($fdata['post_id']);
                $user = $uModel->getUser($fdata['poster_id']);
                $username = $user['firstName'] . " " . $user['lastName'];
				$uplant = $pmodel->getPlant($user['plantId']);
				$uplantname = $uplant['plantName'];
?>		
		


				<div class = 'tendivf search-result' id = 'tengroupf<?php echo $i; ?>' onmouseover="glow(this,'f0f7ec'); this.style.borderLeft='solid 2px #2e4e68';" onmouseout="unglow(this); this.style.borderLeft='none';">
        		<b><div class='search-result-details'>
				<div class='search-result-ss'><?php echo "<a href = '" . $fdata['url'] . "'>" . $fdata['post_subject'] . "</a>"; ?></div>
        		<div class='search-result-gt'>Topic : <?php echo $fdata['topicname']; ?></div>
        		<div class='search-result-plant'>Subject : <?php echo $fdata['post_subject']; ?></div></div></b>
        		<div class='search-result-data'><?php echo $fdata['post_text']; ?></div>
                <div class='search-result-updatedby'><i>Posted by <?php echo "<a href = '/userprofile/view?id=" . $user['id'] . "'>" . $username . "</a> - <a href = '/plant/view?id=" . $user['plantId'] . "'>" . $fdata['userplantname'] . "</a> "; ?></i></div>
                </div>
             
        <?php
                endforeach;
				
					
                if (!count($this->forumData) && !count($this->searchData)) {
                    echo "<center><i>No results to display</i></center>";
                }
        ?>		
        
        <div id = "forum-pagination">
		<?php
			$results = $this->fgr;
			$n = (int)($results/10);
			if($results % 10 != 0)
			{
				$n++;
			}
			if($n!=1)
			{
				for($i=1;$i<=$n;$i++)
				{
					echo "<a href = '#' id = 'forum_paginate_link' onclick = 'fpaginate($i)'>" . $i . "</a>&nbsp&nbsp";
				}
			}
		?>
	</div>
	</div>
</div>

