<?php
$this->jQuery()->enable();
echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');
echo $this->adminId;
echo $this->form;
echo $this->message;
?>

<script type="text/javascript">
    $(document).ready(function(){
	    $("input").blur(function(){
	        var formElementId = ($(this).parent().prev().find('label').attr('for'));
	        doValidation(formElementId,'/hive/public/userprofile/addvalidate/');
	   	});
	});

   function unloadPage(){
       return "Leaving this page will lead to loss of data";
   }   
   window.onbeforeunload = unloadPage;

</script>