<?php
echo $this->headScript()->prependFile($this->baseUrl().'/js/ajaxvalidation.js');
if($this->message == 'Not yet posted')
{
	$this->message = "";
}
else {
	$this->message = "<div class = 'errors'>$this->message</div>";
}
$data = $this->form.$this->message;
$this->tabPane("ConfGall",$data,array('title' => 'Change Password'));
echo $this->tabContainer("ConfGall",array());
?>

<script type="text/javascript">
    $(document).ready(function(){
	    $("input").blur(function(){
	    	if(this.value == "" || this.value == null)
	    	{
	    		return;
	    	}
	        var formElementId = ($(this).parent().prev().find('label').attr('for'));
	        doValidationPlant($(this).attr('id'),'../validation/validate?form=changepassword');
	   });
	});
</script>