<link href="/js/tablecloth/tablecloth.css" rel="stylesheet" type="text/css"/>
<script type='text/javascript' src='/js/tablecloth/tablecloth.js'></script>
<?php
$data="<table  cellspacing='0' cellpadding='0' onmouseover='tablecloth();'>
    
    <tr>
        <td>Name</td>
        <td><b>".$this->profileData['firstName']." ".$this->profileData['lastName']."</b>$this->iscc</td>
    </tr>
    
	<tr>
        <td>Plant</td>
        <td>".$this->uPlantName."</td>
    </tr>
    
    <tr>
        <td>Designation</td>
        <td>".$this->profileData['designation']."</td>
    </tr>

    <tr>
        <td>Phone</td>
        <td>".$this->profileData['phone']."</td>
    </tr>

    <tr>
        <td>Mobile</td>
        <td>".$this->profileData['mobile']."</td>
    </tr>

    <tr>
        <td>E-Mail</td>
        <td><a href = 'mailto:".$this->profileData['email']."'>".$this->profileData['email']."</a></td>
    </tr>
    
</table>";
$lastlogin = Zend_Auth::getInstance()->getStorage()->read()->lastlogin;
$pid = $this->uPlantId;
if($lastlogin == NULL)
{
	$data .= "<center><a href = '/userprofile/index'>&lt;&lt; Back</a>&nbsp;&nbsp;";
	$data .= "<a href = '/plant/edit?id=$pid'>Continue &gt;&gt;</a></center>";
}

$this->tabPane("userdata",$data,array('title' => 'Personal Information'));
echo $this->tabContainer("userdata",array()); 
?>