<?php 
	echo $this->form;
	if($this->message == "")
		echo $this->message;
	else 
		echo "<div class = 'errors'>" . $this->message . "</div>";
?>
<div id = "spinnerimage" style = "display:none">Uploading ... <img src = "/images/spinner.gif"></div>
<script type = "text/javascript" src = "/js/file_ext_check.js"></script>
<script type = "text/javascript">
	
	$("#submitbutton").click(function() {
		document.getElementById("spinnerimage").style.display = "block";
	});
	
</script>
