<?php
	echo $this->form;
?>
<div id = "responsediv"></div>

<script type = "text/javascript">
	/*$("#upload").click(function(){
		var data = {};
		data['title'] = document.getElementById("title").value;
		data['filename'] = document.getElementById("filepath").value;
		var url = "/attachments/upload";
		
		$.post(url,data,function(resp){
	        $('#responsediv').html(resp);
	    });
		
	});*/
</script>