<?php
$existPresList = "<b>Attachments already added to this</b><br><br>";
$pres_str = substr($this->gtdata['presentationId'],0,strlen($this->gtdata['presentationId'])-1);
$pres_array = explode(",",$pres_str);
$this->spinner = "<div id = 'spinnerimage' style = 'display:none'>Uploading ... <img src = '/images/spinner.gif'></div>";
if(count($pres_array) == 0 || (count($pres_array) == 1 && $pres_array[0] == 0))
{
	$existPresList = "";
}
else
{
	$presmodel = new Model_DbTable_Presentation();
	for($i=0;$i<count($pres_array);$i++)
	{
		$pres = $presmodel->getPresentation($pres_array[$i]);
		$existPresList .= "<div id = 'presdiv" . $pres_array[$i] . "'><a href = '/presentation/view?id=" . $pres_array[$i] . "'>" . $pres['title'] . "</a>";
		$gid = $this->gtdata['id'];
		$existPresList .= "<input type = 'button' onClick = 'unlink($pres_array[$i],$gid)' class = 'gt-delete' value = ''></form></div>";
	}
}
echo $this->headScript()->prependFile($this->baseUrl().'/js/tiny_mce/tiny_mce.js');
$this->jQuery()->enable();
if($this->message != "")
	$this->message = "<br><div class ='errors'>" . $this->message . "</div>";
else {
	$this->message = "";
}
$this->tabPane("LTEEdit",$existPresList . $this->form . $this->message  . $this->spinner ,array('title' => 'LTE Edit'));
echo "<div id = 'ssid' style = 'display:none'>" . $this->gtdata['subSysId'] . "</div>";
echo $this->tabContainer("LTEEdit",array());
?>
<script type = "text/javascript" src = "/js/gtdata_checkext.js"></script>
<script type="text/javascript" src='/js/tinyMCEinit.js'></script>
<script type = "text/javascript" src = "/js/multiattach.js"></script>
<script type = "text/javascript">	
	function unlink(pid,gid)
	{
		url = "/presentation/unlink";
		var data = {};
		data['id'] = pid;
		data['gtdataid'] = gid;
		$.post(url,data,function(resp){
	        $('#presentationId').html(resp);
	    });
	    document.getElementById("presdiv" + pid).style.display = "none";
	}
	$(document).ready(function(){
	var sid = document.getElementById("sysId").value;
	var ssid = document.getElementById("ssid").innerHTML;
	if(sid != "" && sid != 0)
	{
       $.ajax({
            type: "POST",
            data: "id=" + sid + "&ssid=" + ssid,
            url: "/findings/index",
            success: function(msg){
                if (msg != ''){
                    $("#subSysId").html(msg).show();
                }
            }
       });
	}
	$("#submitbutton").click(function() {
		var file = document.getElementById("content").value;
		if (file != "")
		{
			document.getElementById("spinnerimage").style.display = "block";
		}
	});
    $("#sysId").change( function() {
        $.ajax({
            type: "POST",
            data: "id=" + $(this).val(),
            url: "/findings/index",
            success: function(msg){
                if (msg != ''){
                    $("#subSysId").html(msg).show();
                    
                }
            }
        });
    });
});
</script>